name: ncatest.cx.js
 
on:
  push:
    branches:
      - main
  schedule:   
    - cron: '27 * * * *'   #国际标准时间，北京时间+8，即下午1点钟
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
		
    - name: Update paper list
      run: |
        python cj.py
		
