name: ncatest.cx.js
 
on:
  push:
    branches:
      - main
  schedule:   
    - cron: '10 * * * *'   #国际标准时间，北京时间+8，即下午1点钟

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: curl http://cj.liuxiaohai.xyz/index.php?s=/Admin/Index/caiji
